sicoapp/urls.py
from django.urls import path
from . import views

app_name = 'sicomec'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

    path('driver/create', views.driver_create_view, name='driver_create'),
    path('driver/update/<str:id>', views.driver_update_view, name='driver_update'),
    path('driver/list', views.driver_list_view, name='driver_list'),
    path('driver/delete/<str:id>', views.driver_delete_view, name='driver_delete'),

    path('vehicle/create', views.vehicle_create_view, name='vehicle_create'),
    path('vehicle/update/<str:id>', views.vehicle_update_view, name='vehicle_update'),
    path('vehicle/list', views.vehicle_list_view, name='vehicle_list'),
    path('vehicle/delete/<str:id>', views.vehicle_delete_view, name='vehicle_delete'),

    path('fueltap/create', views.fueltap_create_view, name='fueltap_create'),
    path('fueltap/update/<str:id>', views.fueltap_update_view, name='fueltap_update'),
    path('fueltap/list', views.fueltap_list_view, name='fueltap_list'),
    path('fueltap/delete/<str:id>', views.fueltap_delete_view, name='fueltap_delete'),

    path('buy_order/create', views.buy_order_create_view, name='buy_order_create'),
    path('buy_order/update/<str:id>', views.buy_order_update_view, name='buy_order_update'),
    path('buy_order/list', views.buy_order_list_view, name='buy_order_list'),
    path('buy_order/delete/<str:id>', views.buy_order_delete_view, name='buy_order_delete'),

    path('fuel_order/create', views.fuel_order_create_view, name='fuel_order_create'),
    # path('fuel_order/update/<str:id>', views.fuel_order_update_view, name='fuel_order_update'),
    path('fuel_order/list', views.fuel_order_list_view, name='fuel_order_list'),
    path('fuel_order/generate_fuel_order_pdf/<str:id>', views.generate_fuel_order_pdf, name='generate_fuel_order_pdf'),
    path('fuel_order/generate_control_card_pdf/<uuid:order_id>/', views.generate_control_card_pdf, name='generate_control_card_pdf'),
    path('fuel_order/delete/<str:id>', views.fuel_order_delete_view, name='fuel_order_delete'),
    path('fuel_order/control_card', views.control_card_view, name='control_card'),

    path('ballot/create', views.ballot_create_view, name='ballot_create'),
    path('ballot/update/<str:id>', views.ballot_update_view, name='ballot_update'),
    path('ballot/list_scheduled', views.ballot_list_scheduled_view, name='ballot_list_scheduled'),
    path('ballot/list_complete', views.ballot_list_complete_view, name='ballot_list_complete'),
    path('ballot/mark_return', views.ballot_mark_return_view, name='ballot_mark_return'),
    path('ballot/mark_return/update', views.update_return_datetime, name='update_return_datetime'),
    path('ballot/generate_ballot_pdf/<str:id>', views.generate_ballot_pdf, name='generate_ballot_pdf'),
    path('ballot/delete/<uuid:id>/', views.ballot_delete_view, name='ballot_delete'),
    path('ballot/report/', views.ballot_report_view, name='ballot_report'),
    
    path('notification/list', views.notification_list_view, name='notification_list'),
    path('notification/count', views.notification_count_view, name='notification_count'),

    path('get_vehicle_details/<str:id>', views.get_vehicle_details_view, name='get_vehicle_details'),
    path('get_buy_order_details/<uuid:id_buy_order>', views.get_buy_order_details_view, name='get_buy_order_details'),
    path('get_buy_order_uuid/<str:order_identifier>/', views.get_buy_order_uuid_view, name='get_buy_order_uuid'),
    path('get_fuel_orders/<uuid:id_buy_order>', views.get_fuel_orders_view, name='get_fuel_orders'),
    path('get_driver_details/<uuid:id>', views.get_driver_details_view, name='get_driver_details'),

    
]

sicomec/urls.py
from django.contrib import admin
from django.urls import path, include
from sicoapp.views import error_403

urlpatterns = [
    path('sicomec/admin/', admin.site.urls),
    path('sicomec/', include('sicoapp.urls')),
]

handler404 = 'sicoapp.views.error_404'
handler403 = error_403

sicoapp/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.core.validators import RegexValidator
from django.utils import timezone
from datetime import datetime
from django.core.exceptions import ValidationError

# STATIC MODELS --------------------------------------------------------------------

class LicenseCategory(models.Model):
    name = models.CharField(max_length=6, null=False, blank=False)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "LicenseCategory"
        verbose_name = "Categoría de Licencia"
        verbose_name_plural = "Categoría de Licencias"
    
class Fuel(models.Model):
    name = models.CharField(max_length=10, null=False, blank=False)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "Fuel"
        verbose_name = "Tipo de Combustible"
        verbose_name_plural = "Tipo de Combustibles"

class TypeVehicle(models.Model):
    name = models.CharField(max_length=10, null=False, blank=False)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "TypeVehicle"
        verbose_name = "Tipo de Vehículo"
        verbose_name_plural = "Tipo de Vehículos"


# DRIVER MODEL --------------------------------------------------------------------

dni_validator = RegexValidator(
    regex=r'^[0-9]{8}$', 
    message="El DNI debe ser numérico de 8 dígitos"
)

license_validator = RegexValidator(
    regex=r'^[A-Z][0-9]{8}$',
    message="La licencia debe comenzar con una letra (A-Z) seguido del DNI"
)

class Driver(models.Model):
    ORIGIN_CHOICES = [
        ('DRTC', 'DRTC'),
        ('EXTERNO', 'EXTERNO'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    dni = models.CharField(max_length=8, verbose_name='DNI', unique=True, validators=[dni_validator])
    name = models.CharField(max_length=20, verbose_name='Nombres', null=False, blank=False)
    last_name = models.CharField(max_length=30, verbose_name='Apellidos', null=False, blank=False)
    license = models.CharField(max_length=9, verbose_name='N° Licencia', unique=True, validators=[license_validator])
    category = models.ForeignKey(LicenseCategory, on_delete=models.PROTECT, verbose_name='Categoría')
    expiration = models.DateField(verbose_name='Vencimiento Licencia', auto_now=False)
    validity = models.BooleanField(default=True)
    available = models.BooleanField(default=True, verbose_name='Disponible')
    justify = models.TextField(verbose_name='Justificación',null=True, blank=True)
    origin = models.CharField(max_length=10, choices=ORIGIN_CHOICES, verbose_name='Origen', default='DRTC')
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.name} {self.last_name}'

    class Meta:
        db_table = "Driver"
        verbose_name = "Conductor"
        verbose_name_plural = "Conductores"

    def save(self, *args, **kwargs):
        if self.name:
            self.name = self.name.upper()
        if self.last_name:
            self.last_name = self.last_name.upper()
        if self.license:
            self.license = self.license.upper()
        if self.justify:
            self.justify = self.justify.upper()
        super(Driver, self).save(*args, **kwargs)



# VEHICLE MODEL --------------------------------------------------------------------

def validate_year(value):
    current_year = datetime.now().year
    if value < 1975 or value > current_year:  
        raise ValidationError(f'{value} año no válido')

class Vehicle(models.Model):
    ORIGIN_CHOICES = [
        ('DRTC', 'DRTC'),
        ('EXTERNO', 'EXTERNO'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    plate = models.CharField(max_length=6, verbose_name='Placa', unique=True, null=False, blank=False)
    type = models.ForeignKey(TypeVehicle, on_delete=models.PROTECT, verbose_name='Clase')
    name = models.CharField(max_length=30, verbose_name='Tipo', null=False, blank=False)
    brand = models.CharField(max_length=20, verbose_name='Marca', null=False, blank=False)
    chassis = models.CharField(max_length=17, verbose_name='Chasis', null=True, blank=True)
    model = models.CharField(max_length=20, verbose_name='Modelo', null=False, blank=False)
    production = models.IntegerField(verbose_name='Año Fabricación',  null=False, blank=False, validators=[validate_year])
    fuel = models.ForeignKey(Fuel, on_delete=models.PROTECT, verbose_name='Combustible')
    mileage = models.PositiveIntegerField(verbose_name='Kilometraje',default=0, null=True, blank=True)
    hourometer = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name='Horómetro', null=True, blank=True)
    soat = models.DateField(verbose_name='Emisión SOAT', auto_now=False, null=True, blank=True)
    citv = models.DateField(verbose_name='Emisión CITV', auto_now=False, null=True, blank=True)
    available = models.BooleanField(default=True, verbose_name='Disponible')
    justify = models.TextField(verbose_name='Justificación',null=True, blank=True)
    origin = models.CharField(max_length=10, choices=ORIGIN_CHOICES, verbose_name='Origen', default='DRTC')
    maintenance = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.plate
    
    class Meta:
        db_table = "Vehicle"
        verbose_name = "Vehículo"
        verbose_name_plural = "Vehículos"
    
    def save(self, *args, **kwargs):
        if self.plate:
            self.plate = self.plate.upper()
        if self.name:
            self.name = self.name.upper()
        if self.brand:
            self.brand = self.brand.upper()
        if self.chassis:
            self.chassis = self.chassis.upper()
        if self.model:
            self.model = self.model.upper()
        if self.justify:
            self.justify = self.justify.upper()
        super(Vehicle, self).save(*args, **kwargs)



# FUELTAP MODEL --------------------------------------------------------------------

ruc_validator = RegexValidator(
    regex=r'^[0-9]{11}$', 
    message="El RUC debe ser numérico de 11 dígitos"
)

class FuelTap(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    ruc = models.CharField(max_length=11, verbose_name='RUC', unique=True,  null=False, blank=False, validators=[ruc_validator])
    business_name = models.TextField(verbose_name='Razón Social', null=False, blank=False)
    address = models.TextField(verbose_name='Dirección', null=False, blank=False)
    email =  models.EmailField(max_length=254, verbose_name='Email',  null=True, blank=True)
    phone = models.CharField(max_length=30, verbose_name='Teléfono',  null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.business_name
    
    class Meta:
        db_table = "FuelTap"
        verbose_name = "Grifo"
        verbose_name_plural = "Grifos"
    
    def save(self, *args, **kwargs):
        if self.business_name:
            self.business_name = self.business_name.upper()
        if self.address:
            self.address = self.address.upper()
        if self.email:
            self.email = self.email.upper()
        super(FuelTap, self).save(*args, **kwargs)



# BUY ORDER MODEL --------------------------------------------------------------------

class BuyOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    order =  models.CharField(max_length=9, verbose_name='N° O/C', unique=True,  null=False, blank=False)
    user_area = models.TextField(verbose_name='Área Usuaria',null=False, blank=False)
    fueltap = models.ForeignKey(FuelTap, on_delete=models.PROTECT, verbose_name='Proveedor')
    fuel = models.ForeignKey(Fuel, on_delete=models.PROTECT, verbose_name='Combustible')
    stock = models.DecimalField(max_digits=10, decimal_places=2, default=0,verbose_name='Cantidad Comprada', null=False, blank=False)
    residue = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    date = models.DateField(verbose_name='Fecha O/C', auto_now=False)
    detail = models.TextField(verbose_name='Detalle',null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.order
    
    class Meta:
        db_table = "BuyOrder"
        verbose_name = "Orden de Compra"
        verbose_name_plural = "Órdenes de compras"
    
    def get_fuel_code(self):
        fuel_codes = {
            'G. REGULAR': 'GR',
            'G. PREMIUM': 'GP',
            'DIESEL': 'DS',
        }
        return fuel_codes.get(self.fuel.name, '')
    
    def save(self, *args, **kwargs):
        if self.user_area:
            self.user_area = self.user_area.upper()
        if self.detail:
            self.detail = self.detail.upper()

        if self.fuel and self.order:
            fuel_code = self.get_fuel_code()
            if self.order[-2:] in ['GP', 'GR', 'DS']:  
                self.order = self.order[:-2]  

            self.order = f"{self.order}{fuel_code}"

        super(BuyOrder, self).save(*args, **kwargs)



# FUEL ORDER MODEL --------------------------------------------------------------------

voucher_validator = RegexValidator(
    regex=r'^[0-9]{1,7}$', 
    message="El vale debe ser numérico"
)

class FuelOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    code = models.CharField(max_length=10, unique=True, editable=False) 
    fueltap = models.TextField(verbose_name='Proveedor', null=False, blank=False)

sicoapp/templates/fuel_orders/fuel_order_control_card.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Tarjeta de Control | SICOMEC{% endblock %}

{% block content %}
<div class="row">
    <section class="col-md-12 mt-5">
        <h3 class="text-center mb-3" >Tarjeta de Control</h3>
        <form method="GET" action="" class="d-flex flex-row flex-wrap justify-content-between align-items-center" autocomplete="off">
            <div class="mb-3">
                <label for="orderInput"></label> 
                <div class="input-group">
                    <input type="search" name="orderInput" class="form-control" placeholder="Buscar O/C" aria-label="Buscar" autofocus id="id_orderInput" style="width: 150px;">
                    <button class="btn btn-primary" type="submit" title="Buscar">
                        <i class="bi bi-search mx-1" style="font-size: 1rem;"></i>
                    </button>
                </div>
            </div>
            <div class="mb-3">
                <label for="user_area">Área Usuaria</label> 
                <textarea name="user_area" cols="30" rows="1" readonly="readonly" style="background-color: rgb(248 249 251); max-width: 250px;" class="textarea form-control" id="id_user_area"></textarea>
            </div>
            <div class="mb-3">
                <label for="fueltap">Proveedor</label>
                <textarea name="fueltap" cols="20" rows="1" id="id_fueltap" readonly="readonly" style="background-color: rgb(248 249 251);" class="textarea form-control" ></textarea>
            </div>
            <div class="mb-3">
                <label for="fuel">Combustible</label>
                <input type="text" name="fuel" id="id_fuel" readonly="readonly" style="background-color: rgb(248 249 251); pointer-events: none; max-width: 130px;" class="form-control" value="" >
            </div>
            <div class="mb-3">
                <label for="stock">Entrada</label>
                <input type="text" name="stock" id="id_stock" readonly="readonly" style="background-color: rgb(248 249 251); pointer-events: none; max-width: 130px;" class="form-control" value="" >
            </div>
            <div class="mb-3">
                <label for="residue">Saldo</label>
                <input type="text" name="residue" id="id_residue" readonly="readonly" style="background-color: rgb(248 249 251); pointer-events: none; max-width: 130px;" class="form-control" value="" >
            </div>
            <div class="mb-3" style="padding-top: 25px;">
                <a class="btn btn-primary {% if is_uquery %}d-none{% endif %}" data-base-url="/sicomec/fuel_order/generate_control_card_pdf/" href="#" target="_blank" id="printButton">
                    <i class="bi bi-printer-fill" title="Imprimir"></i>
                </a>
            </div>
            
        </form>
    </section> 

    <section class="col-md-12 my-3" style="margin-bottom: 80px;">
            <div class="card card-body table-responsive">
                <table class="datatable display">
                </table>
            </div>
    </section>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/fuel_order_control_table.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var fields = [
            { id: "id_orderInput", transform: "toUpperCase" },
        ];
    
        function transformInput(event, transform) {
            if (transform === "toUpperCase") {
                event.target.value = event.target.value.toUpperCase();
            }
        }
    
        fields.forEach(function(field) {
            var element = document.getElementById(field.id);
    
            if (field.transform === "toUpperCase") {
                element.addEventListener("input", function(event) {
                    transformInput(event, field.transform);
                });
            }
        });

        // START MAXLENGTH 9 FOR BUY ORDER
        var orderField = document.querySelector('input[name="orderInput"]');

        if (orderField) {
            orderField.addEventListener('input', function(e) {
                if (e.target.value.length > 9) {
                    e.target.value = e.target.value.slice(0, 9);
                }
            });
        }
        // END MAXLENGTH 9 FOR BUY ORDER
    });
</script> 
{% endblock %}

sicoapp/templates/fuel_orders/fuel_order_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Registrar Pedido de Combustible | SICOMEC{% endblock %}

{% block content %}
    <div class="row">
        {% if request.GET.success == 'true' %}
            <section class="col-md-8 offset-md-2 mt-5">
                <div class="d-flex justify-content-center">
                    <a  href="{% url 'sicomec:generate_fuel_order_pdf' id=request.GET.fuel_order_id %}" target="_blank" class="btn btn-primary w-50 mx-1">
                        <i class="bi bi-printer-fill mx-1"></i>
                        Imprimir
                    </a>
                    <a href="{% url 'sicomec:fuel_order_list' %}" class="btn btn-primary w-50 mx-1">
                        <i class="bi bi-file-earmark-text-fill mx-1"></i>
                        Ver lista
                    </a>
                </div>
            </section>
        {% else %}
            <section class="col-md-8 offset-md-2 my-5">
                <h3 class="text-center mb-3">Registrar Pedido de Combustible</h3>
                <form method="POST" enctype="multipart/form-data" class="card card-body mb-5" autocomplete="off">
                    {% csrf_token %}
                    <input type="hidden" id="form-instance-id" data-instance-id="{{ form.instance.code }}">
                    {% crispy form %}
                </form>
            </section>
        {% endif %}
    </div>
{% endblock %}
 
{% block js %}
    {% if not request.GET.success == 'true' %}
    <script src="{% static 'js/fuel_order_form.js' %}"></script>
    {% endif %}
{% endblock %}

sicoapp/templates/fuel_orders/fuel_order_list.html
{% extends 'base.html' %}
{% load static %}
{% load format_filters %}

{% block title %}Buscar Pedido de Combustible | SICOMEC{% endblock %}

{% block content %}
<div class="row">
    <section class="col-md-6 offset-md-3 mt-5">
        <h3 class="text-center mb-3" >Buscar Pedido de Combustible</h3>
    </section> 

    <section class="col-md-12" style="margin-bottom: 80px;">
            <div class="card card-body table-responsive">
                <table class="datatable display">
                    <thead>
                        <tr>
                            {% if is_super_admin or is_cadmin or is_coperator %}
                                <th>Acciones</th>
                            {% endif %}

                            <th>Proveedor</th>
                            <th>N° Orden</th>
                            <th>Conductor</th>
                            <th>Placa</th>
                            <th>Cant.</th>
                            <th>Combustible</th>
                            <th>N° Vale</th>
                            <th>Código</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for fuel_order in fuel_orders %}
                            <tr class="" data-canceled="{% if fuel_order.canceled %}true{% else %}false{% endif %}">
                                {% if is_super_admin or is_cadmin or is_coperator %}
                                    <td>
                                        <div class="btn-group">
                                            {% if fuel_order.show_buttons %}
                                            <a class="btn btn-sm btn-outline-primary" href="{% url 'sicomec:generate_fuel_order_pdf' fuel_order.id %}" target="_blank">
                                                <i class="bi bi-printer-fill" title="Imprimir"></i>
                                            </a>
                                        {% comment %} <a class="btn btn-sm btn-outline-primary " href="{% url 'sicomec:fuel_order_update' fuel_order.id %}?q={{ query }}">
                                            <i class="bi bi-pencil-fill" title="Editar"></i>
                                            </a> {% endcomment %}
                                            {% if is_super_admin or is_cadmin %}
                                                <a class="btn btn-sm btn-outline-danger" href="#" onclick="deleteRecord('/sicomec/fuel_order/delete', '{{ fuel_order.id }}', '', 'canceled')" title="Anular">
                                                    <i class="bi bi-x-circle-fill"></i>
                                                </a>
                                            {% endif %}
                                            
                                            {% else %}
                                            <a class="btn btn-sm btn-outline-primary" href="{% url 'sicomec:generate_fuel_order_pdf' fuel_order.id %}" target="_blank">
                                                <i class="bi bi-printer-fill" title="Imprimir"></i>
                                            </a>
                                            {% comment %} <button class="btn btn-sm btn-outline-primary" disabled>
                                                <i class="bi bi-pencil-fill"></i>
                                                </button> {% endcomment %}
                                                <button class="btn btn-sm btn-outline-danger" disabled>
                                                    <i class="bi bi-x-circle-fill"></i>
                                                </button>
                                                
                                            {% endif %}
                                            </div>
                                    </td>
                                {% endif %}
                                <td class="align-middle">
                                    <span class="d-inline-block text-truncate align-middle" style="max-width: 200px;">
                                        {{ fuel_order.fueltap }}
                                    </span>
                                </td>
                                <td class="align-middle">{{ fuel_order.order }}</td>
                                <td class="align-middle">{{ fuel_order.driver|default_if_none:"" }}</td>
                                <td class="align-middle">{{ fuel_order.plate|default_if_none:"" }}</td>
                                <td class="align-middle">
                                    {{ fuel_order.quantity|format_number }}
                                </td>
                                <td class="align-middle">{{ fuel_order.fuel }}</td>
                                <td class="align-middle">{{ fuel_order.voucher }}</td>
                                <td class="align-middle">{{ fuel_order.code }}</td>
                            </tr>   
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </section>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/datatables.js' %}"></script>
{% endblock  %}

sicoapp/templates/fuel_orders/fuel_order_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Actualizar Pedido de Combustible | SICOMEC{% endblock %}

{% block content %}
    <div class="row">
        <section class="col-md-8 offset-md-2 my-5">
            <h3 class="text-center mb-3">
                <a class="btn btn-sm" href="{% url 'sicomec:fuel_order_list' %}" title="Regresar" style="background-color: #072e5e;">
                    <i class="bi bi-arrow-left mx-1" style="font-size: 1rem; color: #fff;"></i>
                </a>
                Actualizar Pedido de Combustible
            </h3>
            <form method="POST" enctype="multipart/form-data" class="card card-body mb-5" autocomplete="off">
                {% csrf_token %}
                {% comment %} <input type="hidden" id="form-instance-id" data-instance-id="{{ form.instance.pk }}"> {% endcomment %}
                {% crispy form %}
            </form>
        </section>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/fuel_order_form.js' %}"></script>
{% endblock %}