sicoapp/urls.py
from django.urls import path
from . import views

app_name = 'sicomec'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

    path('driver/create', views.driver_create_view, name='driver_create'),
    path('driver/update/<str:id>', views.driver_update_view, name='driver_update'),
    path('driver/list', views.driver_list_view, name='driver_list'),
    path('driver/delete/<str:id>', views.driver_delete_view, name='driver_delete'),

    path('vehicle/create', views.vehicle_create_view, name='vehicle_create'),
    path('vehicle/update/<str:id>', views.vehicle_update_view, name='vehicle_update'),
    path('vehicle/list', views.vehicle_list_view, name='vehicle_list'),
    path('vehicle/delete/<str:id>', views.vehicle_delete_view, name='vehicle_delete'),

    path('fueltap/create', views.fueltap_create_view, name='fueltap_create'),
    path('fueltap/update/<str:id>', views.fueltap_update_view, name='fueltap_update'),
    path('fueltap/list', views.fueltap_list_view, name='fueltap_list'),
    path('fueltap/delete/<str:id>', views.fueltap_delete_view, name='fueltap_delete'),

    path('buy_order/create', views.buy_order_create_view, name='buy_order_create'),
    path('buy_order/update/<str:id>', views.buy_order_update_view, name='buy_order_update'),
    path('buy_order/list', views.buy_order_list_view, name='buy_order_list'),
    path('buy_order/delete/<str:id>', views.buy_order_delete_view, name='buy_order_delete'),

    path('fuel_order/create', views.fuel_order_create_view, name='fuel_order_create'),
    # path('fuel_order/update/<str:id>', views.fuel_order_update_view, name='fuel_order_update'),
    path('fuel_order/list', views.fuel_order_list_view, name='fuel_order_list'),
    path('fuel_order/generate_fuel_order_pdf/<str:id>', views.generate_fuel_order_pdf, name='generate_fuel_order_pdf'),
    path('fuel_order/generate_control_card_pdf/<uuid:order_id>/', views.generate_control_card_pdf, name='generate_control_card_pdf'),
    path('fuel_order/delete/<str:id>', views.fuel_order_delete_view, name='fuel_order_delete'),
    path('fuel_order/control_card', views.control_card_view, name='control_card'),

    path('ballot/create', views.ballot_create_view, name='ballot_create'),
    path('ballot/update/<str:id>', views.ballot_update_view, name='ballot_update'),
    path('ballot/list_scheduled', views.ballot_list_scheduled_view, name='ballot_list_scheduled'),
    path('ballot/list_complete', views.ballot_list_complete_view, name='ballot_list_complete'),
    path('ballot/mark_return', views.ballot_mark_return_view, name='ballot_mark_return'),
    path('ballot/mark_return/update', views.update_return_datetime, name='update_return_datetime'),
    path('ballot/generate_ballot_pdf/<str:id>', views.generate_ballot_pdf, name='generate_ballot_pdf'),
    path('ballot/delete/<uuid:id>/', views.ballot_delete_view, name='ballot_delete'),
    path('ballot/report/', views.ballot_report_view, name='ballot_report'),
    
    path('notification/list', views.notification_list_view, name='notification_list'),
    path('notification/count', views.notification_count_view, name='notification_count'),

    path('get_vehicle_details/<str:id>', views.get_vehicle_details_view, name='get_vehicle_details'),
    path('get_buy_order_details/<uuid:id_buy_order>', views.get_buy_order_details_view, name='get_buy_order_details'),
    path('get_buy_order_uuid/<str:order_identifier>/', views.get_buy_order_uuid_view, name='get_buy_order_uuid'),
    path('get_fuel_orders/<uuid:id_buy_order>', views.get_fuel_orders_view, name='get_fuel_orders'),
    path('get_driver_details/<uuid:id>', views.get_driver_details_view, name='get_driver_details'),

    
]

sicomec/urls.py
from django.contrib import admin
from django.urls import path, include
from sicoapp.views import error_403

urlpatterns = [
    path('sicomec/admin/', admin.site.urls),
    path('sicomec/', include('sicoapp.urls')),
]

handler404 = 'sicoapp.views.error_404'
handler403 = error_403

sicoapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from .models import Driver, Vehicle, FuelTap, Ballot, Notification, BuyOrder, FuelOrder
from .forms import DriverForm, VehicleForm, FuelTapForm, BallotForm, BuyOrderForm, FuelOrderForm
from django.contrib import messages
from django.db.models import Q, Sum
from django.utils import timezone
from datetime import datetime
import pytz
from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
from babel.dates import format_datetime
from django.http import JsonResponse
from django.http import Http404
import re
from django.db import IntegrityError
from django.templatetags.static import static

# ************************************ GENERAL VIEWS ************************************

# HOME ---------------------------------------------------------------->
def home_view(request):
    return render(request, 'index.html')

# LOGIN --------------------------------------------------------------->
def login_view(request):
    if request.user.is_authenticated:
        return redirect('sicomec:home')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('sicomec:home')
            else:
                form.add_error(None, 'Usuario o contraseña incorrecto')
    else:
        form = AuthenticationForm(
            initial={'username': request.POST.get('username', '')})

    return render(request, 'login.html', {'form': form})

# LOGOUT --------------------------------------------------------------->
@login_required
def logout_view(request):
    logout(request)
    return redirect('sicomec:home')



# ************************************ DRIVER VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_driver', raise_exception=True)
def driver_create_view(request):
    if request.method == 'POST':
        form = DriverForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '¡Registro exitoso!')
            return redirect('sicomec:driver_list')  
    else:
        form = DriverForm()
    
    return render(request, 'drivers/driver_create.html', {'form': form})

# UPDATE ----------------------------------------------------------------->
@login_required
@permission_required('sicoapp.change_driver', raise_exception=True)
def driver_update_view(request, id):
    driver = get_object_or_404(Driver, pk=id)

    if request.method == 'POST':
        form = DriverForm(request.POST, instance=driver)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Actualización exitosa!')
            return redirect('sicomec:driver_list')
    else:
        formatted_expiration = driver.expiration.strftime('%Y-%m-%d')
        form = DriverForm(instance=driver, initial={'expiration': formatted_expiration})

    return render(request, 'drivers/driver_update.html', {'form': form, })

# LIST ------------------------------------------------------------------->
@login_required
@permission_required('sicoapp.view_driver', raise_exception=True)
def driver_list_view(request):
    results = Driver.objects.all()

    return render(request, 'drivers/driver_list.html', 
                {
                    'drivers': results,
                })

# DELETE ------------------------------------------------------------------>
@login_required
@permission_required('sicoapp.delete_driver', raise_exception=True)
def driver_delete_view(request, id):
    driver = get_object_or_404(Driver, pk=id)

    if Ballot.objects.filter(driver=driver.pk).exists():
        messages.warning(request, 'Conductor tiene papeleta asociada')
        return redirect('sicomec:driver_list')  

    if FuelOrder.objects.filter(driver=driver.pk).exists():
        messages.warning(request, 'Conductor tiene orden de compra asociada')
        return redirect('sicomec:driver_list')  
    
    driver.delete()
    messages.success(request, '¡Registro eliminado!')

    return redirect('sicomec:driver_list')  



# ************************************ VEHICLE VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_vehicle', raise_exception=True)
def vehicle_create_view(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '¡Registro exitoso!')
            return redirect('sicomec:vehicle_list')  
    else:
        form = VehicleForm()
    
    return render(request, 'vehicles/vehicle_create.html', {'form': form})

# UPDATE ----------------------------------------------------------------->
@login_required
@permission_required('sicoapp.change_vehicle', raise_exception=True)
def vehicle_update_view(request, id):
    vehicle = get_object_or_404(Vehicle, pk=id)

    if request.method == 'POST':
        form = VehicleForm(request.POST, instance=vehicle)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Actualización exitosa!')
            return redirect('sicomec:vehicle_list')
    else:
        form = VehicleForm(instance=vehicle, initial={
                            'soat': vehicle.soat.strftime('%Y-%m-%d') if vehicle.soat else '',
                            'citv': vehicle.citv.strftime('%Y-%m-%d') if vehicle.citv else '',
                            })

    return render(request, 'vehicles/vehicle_update.html', {'form': form,})

# LIST ------------------------------------------------------------------->
@login_required
@permission_required('sicoapp.view_vehicle', raise_exception=True)
def vehicle_list_view(request):
    results = Vehicle.objects.all()

    return render(request, 'vehicles/vehicle_list.html', {'vehicles': results,})

# DELETE ------------------------------------------------------------------>
@login_required
@permission_required('sicoapp.delete_vehicle', raise_exception=True)
def vehicle_delete_view(request, id):
    vehicle = get_object_or_404(Vehicle, pk=id)

    if Ballot.objects.filter(plate=vehicle.id).exists():
        messages.warning(request, 'Vehículo tiene papeleta asociada')
        return redirect('sicomec:vehicle_list')  

    if FuelOrder.objects.filter(plate=vehicle.id).exists():
        messages.warning(request, 'Vehículo tiene órden de compra asociada')
        return redirect('sicomec:vehicle_list')  
    
    vehicle.delete()
    messages.success(request, '¡Registro eliminado!')

    return redirect('sicomec:vehicle_list')  



# ************************************ FUELTAP VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_fueltap', raise_exception=True)
def fueltap_create_view(request):
    if request.method == 'POST':
        form = FuelTapForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '¡Registro exitoso!')
            return redirect('sicomec:fueltap_list')  
    else:
        form = FuelTapForm()
    
    return render(request, 'fueltaps/fueltap_create.html', {'form': form})

# UPDATE ----------------------------------------------------------------->
@login_required
@permission_required('sicoapp.change_fueltap', raise_exception=True)
def fueltap_update_view(request, id):
    fueltap = get_object_or_404(FuelTap, pk=id)

    if request.method == 'POST':
        form = FuelTapForm(request.POST, instance=fueltap)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Actualización exitosa!')
            return redirect('sicomec:fueltap_list')
    else:
        form = FuelTapForm(instance=fueltap)

    return render(request, 'fueltaps/fueltap_update.html', {'form': form, })

# LIST ------------------------------------------------------------------->
@login_required
@permission_required('sicoapp.view_fueltap', raise_exception=True)
def fueltap_list_view(request):
    results = FuelTap.objects.all()

    return render(request, 'fueltaps/fueltap_list.html', {'fueltaps': results, })

# DELETE ------------------------------------------------------------------>
@login_required
@permission_required('sicoapp.delete_fueltap', raise_exception=True)
def fueltap_delete_view(request, id):
    fueltap = get_object_or_404(FuelTap, pk=id)

    if BuyOrder.objects.filter(fueltap=fueltap.pk).exists():
        messages.warning(request, 'Proveedor tiene orden de compra asociada')
    
    else:
        fueltap.delete()
        messages.success(request, '¡Registro eliminado!')

    return redirect('sicomec:fueltap_list')  



# ************************************ BUY ORDER VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_buyorder', raise_exception=True)
def buy_order_create_view(request):
    if request.method == 'POST':
        form = BuyOrderForm(request.POST)
        if form.is_valid():

            stock_value = form.cleaned_data['stock']
            buy_order_instance = form.save(commit=False)

sicoapp/templates/includes/about.html
{% load static %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background: rgb(248, 249, 250);">
                <img src="{% static 'images/logo_sicomec_sm.png' %}" alt="SICOMEC" title="SICOMEC" height="30" />
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Bienvenido al Sistema Integral de Control de Unidades Motorizadas y Combustibles - SICOMEC, plataforma diseñada para gestionar de manera eficiente el control de salida de vehículos y combustibles en la Dirección Regional de Transportes y Comunicaciones de Apurímac - DRTCA. 
                </div>
                <div class="modal-footer" style="justify-content: flex-start;">
                    <p class="fst-italic">Si tienes preguntas, comentarios o necesitas asistencia, no dudes en contactarnos. DRTCA - Oficina de Tecnología de Información y Sistemas (OTIS).</p>
                    <span style="font-size: .9rem;"><b>Versión 1.0 - 2024</b></span>
                </div>
        </div>
    </div>
</div>

sicoapp/templates/includes/footer.html
{% load static %}
<div id="footer" class="fixed-bottom d-flex align-items-center justify-content-center">
    <div class="logo">
      <a href="https://www.gob.pe/regionapurimac" target="_blank">
        <img src="{% static 'images/gra.png' %}" alt="Gobierno Regional de Apurímac" title="Gobierno Regional de Apurímac" />
      </a>
      <a href="https://drtcapurimac.gob.pe/" target="_blank">
        <img src="{% static 'images/drta.png' %}" alt="Dirección Regional de Transportes y Comunicaciones Apurímac" title="Dirección Regional de Transportes y Comunicaciones Apurímac" />
      </a>
    </div>

    <span class="text-otis">
      <div class="d-flex" style="height: 20px;">
        <div class="vr me-2"></div>
        <span>Oficina de Tecnología de Información y Sistemas | 2024 - <span class="year"></span></span>
      </div>
    </span>
</div>

sicoapp/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg sticky-top" style="background-color: #fafafa;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'sicomec:home' %}">
            <img src="{% static 'images/logo_sicomec_sm.png' %}" alt="SICOMEC" title="SICOMEC" height="25px" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item fw-semibold">
                    <a class="nav-link active" aria-current="page" href="{% url 'sicomec:home' %}">
                        <i class="bi bi-house-door-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                        Inicio
                    </a>
                </li>
                    <li class="nav-item dropdown fw-semibold">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-person-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                        Conductor
                    </a>
                        <ul class="dropdown-menu">
                            <li>
                                {% if is_super_admin or is_cadmin or is_padmin %}
                                <a class="dropdown-item" href="{% url 'sicomec:driver_create' %}">
                                    <i class="bi bi-plus-lg"></i>
                                    Nuevo Registro
                                </a>
                                {% endif %}
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:driver_list' %}">
                                    <i class="bi bi-search"></i>
                                    Buscar
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown fw-semibold">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-car-front-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                        Vehículo
                    </a>
                        <ul class="dropdown-menu">
                            <li>
                                {% if is_super_admin or is_cadmin or is_padmin %}
                                <a class="dropdown-item" href="{% url 'sicomec:vehicle_create' %}">
                                    <i class="bi bi-plus-lg"></i>
                                    Nuevo Registro
                                </a>
                                {% endif %}
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:vehicle_list' %}">
                                    <i class="bi bi-search"></i>
                                    Buscar
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% if is_super_admin or is_padmin or is_poperator or is_pregistrator or is_uquery %}
                    <li class="nav-item dropdown fw-semibold">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-file-earmark-text-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                            Papeleta
                        </a>
                        <ul class="dropdown-menu">
                            {% if not is_pregistrator and not is_uquery %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'sicomec:ballot_create' %}">
                                        <i class="bi bi-plus-lg"></i>
                                        Nuevo Registro
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:ballot_list_scheduled' %}">
                                    <i class="bi bi-clock"></i>
                                    Programadas
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:ballot_list_complete' %}">
                                    <i class="bi bi-check-lg"></i>
                                    Completadas
                                </a>
                            </li>
                            {% if not is_uquery %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'sicomec:ballot_mark_return' %}">
                                        <i class="bi bi-clock"></i>
                                        Marcar Retorno
                                    </a>
                                </li>
                            {% endif %}
                            {% if not is_pregistrator and not is_uquery %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'sicomec:ballot_report' %}">
                                        <i class="bi bi-printer"></i>
                                        Reporte
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </li>
                {% endif %}

                {% if is_super_admin or is_cadmin or is_coperator or is_uquery %}
                    <li class="nav-item dropdown fw-semibold">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-fuel-pump-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                            Grifo
                        </a>
                        <ul class="dropdown-menu">
                            {% if not is_uquery and not is_coperator %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'sicomec:fueltap_create' %}">
                                        <i class="bi bi-plus-lg"></i>
                                        Nuevo Registro
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:fueltap_list' %}">
                                    <i class="bi bi-search"></i>
                                    Buscar
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown fw-semibold">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-file-check-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                            Orden Compra
                        </a>
                        <ul class="dropdown-menu">
                            {% if not is_uquery and not is_coperator %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'sicomec:buy_order_create' %}">
                                        <i class="bi bi-plus-lg"></i>
                                        Nuevo Registro
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:buy_order_list' %}">
                                    <i class="bi bi-search"></i>
                                    Buscar
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown fw-semibold">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-file-check-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                            Combustible
                        </a>
                        <ul class="dropdown-menu">
                            {% if not is_uquery %}
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:fuel_order_create' %}">
                                    <i class="bi bi-plus-lg"></i>
                                    Nuevo Pedido
                                </a>
                            </li>
                            {% endif %}

                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:control_card' %}">
                                    <i class="bi bi-fuel-pump"></i>
                                    Tarjeta de Control
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'sicomec:fuel_order_list' %}">
                                    <i class="bi bi-search"></i>
                                    Buscar
                                </a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        <i class="bi bi-info-circle-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                    </a>
                </li> {% endcomment %}
            </ul>

        {% if user.is_authenticated %}
            <div class="d-flex pt-2">
                <p class="mx-2">
                    <i class="bi bi-person-fill" style="font-size: 1.2rem; color: {% if is_super_admin %}#dd4e0a; {% else %}#0a58ca;{% endif %}"></i>
                    <span style="font-size: .7rem; " class="fw-semibold">
                        {% if not user.first_name %}
                            {{ user.username|upper }}
                        {% else %}
                            {{ user.first_name|upper }} {{ user.last_name|upper }}
                        {% endif %}
                    </span>
                    {% for group in user.groups.all %}
                        <span style="font-size: 9px; display: block; text-align: right; color: rgb(195 196 196); position: absolute; top: 38px; right: 76px;">
                        {% if group.name == 'superAdmin' %}
                            {{ group.name }}
                        {% elif group.name == 'pAdministrator' or group.name == 'cAdministrator' %}
                            Administrador
                        {% elif group.name == 'pOperator' or group.name == 'cOperator' %}
                            Operador
                        {% elif group.name == 'pRegistrator' %}
                            Registrador
                        {% else %}
                            Consulta
                        {% endif %}
                        </span>
                    {% endfor %}
                    {% comment %} , {{ user.last_name }} {% endcomment %}
                </p>
                <p>
                    <a href="{% url 'sicomec:logout' %}" class="link-offset-2 link-underline link-underline-opacity-0" style="color: #FF0000;">
                        <i class="bi bi-power" style="font-size: 1.2rem; color: #FF0000;"></i>
                        <span style="font-size: .8rem;" class="fw-semibold text-uppercase">
                        Salir
                        </span>
                    </a>
                </p>
            </div>
        {% else %}
            <div class="d-flex pt-2">
                <p>
                    <a href="{% url 'sicomec:login' %}" class="link-offset-2 mx-3 link-underline link-underline-opacity-0">
                        <i class="bi bi-person-fill" style="font-size: 1.2rem; color: #0a58ca;"></i>
                        Iniciar Sesión
                    </a>
                </p>
            </div>
        {% endif %}
        </div>
    </div>
</nav>

sicoapp/templates/includes/notification_button.html
{% if request.user.is_authenticated %}
    <div class="notification-button-container" id="notificationButtonContainer" style="display: none;">
        <a class="btn btn-primary position-relative" href="{% url 'sicomec:notification_list' %}" id="notificationButton">
            <i class="bi bi-bell-fill"></i>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="notificationBadge">
            0
            <span class="visually-hidden">unread messages</span>
            </span>
        </a>
    </div>
{% endif %}