sicoapp/urls.py
from django.urls import path
from . import views

app_name = 'sicomec'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

    path('driver/create', views.driver_create_view, name='driver_create'),
    path('driver/update/<str:id>', views.driver_update_view, name='driver_update'),
    path('driver/list', views.driver_list_view, name='driver_list'),
    path('driver/delete/<str:id>', views.driver_delete_view, name='driver_delete'),

    path('vehicle/create', views.vehicle_create_view, name='vehicle_create'),
    path('vehicle/update/<str:id>', views.vehicle_update_view, name='vehicle_update'),
    path('vehicle/list', views.vehicle_list_view, name='vehicle_list'),
    path('vehicle/delete/<str:id>', views.vehicle_delete_view, name='vehicle_delete'),

    path('fueltap/create', views.fueltap_create_view, name='fueltap_create'),
    path('fueltap/update/<str:id>', views.fueltap_update_view, name='fueltap_update'),
    path('fueltap/list', views.fueltap_list_view, name='fueltap_list'),
    path('fueltap/delete/<str:id>', views.fueltap_delete_view, name='fueltap_delete'),

    path('buy_order/create', views.buy_order_create_view, name='buy_order_create'),
    path('buy_order/update/<str:id>', views.buy_order_update_view, name='buy_order_update'),
    path('buy_order/list', views.buy_order_list_view, name='buy_order_list'),
    path('buy_order/delete/<str:id>', views.buy_order_delete_view, name='buy_order_delete'),

    path('fuel_order/create', views.fuel_order_create_view, name='fuel_order_create'),
    # path('fuel_order/update/<str:id>', views.fuel_order_update_view, name='fuel_order_update'),
    path('fuel_order/list', views.fuel_order_list_view, name='fuel_order_list'),
    path('fuel_order/generate_fuel_order_pdf/<str:id>', views.generate_fuel_order_pdf, name='generate_fuel_order_pdf'),
    path('fuel_order/generate_control_card_pdf/<uuid:order_id>/', views.generate_control_card_pdf, name='generate_control_card_pdf'),
    path('fuel_order/delete/<str:id>', views.fuel_order_delete_view, name='fuel_order_delete'),
    path('fuel_order/control_card', views.control_card_view, name='control_card'),

    path('ballot/create', views.ballot_create_view, name='ballot_create'),
    path('ballot/update/<str:id>', views.ballot_update_view, name='ballot_update'),
    path('ballot/list_scheduled', views.ballot_list_scheduled_view, name='ballot_list_scheduled'),
    path('ballot/list_complete', views.ballot_list_complete_view, name='ballot_list_complete'),
    path('ballot/mark_return', views.ballot_mark_return_view, name='ballot_mark_return'),
    path('ballot/mark_return/update', views.update_return_datetime, name='update_return_datetime'),
    path('ballot/generate_ballot_pdf/<str:id>', views.generate_ballot_pdf, name='generate_ballot_pdf'),
    path('ballot/delete/<uuid:id>/', views.ballot_delete_view, name='ballot_delete'),
    path('ballot/report/', views.ballot_report_view, name='ballot_report'),
    
    path('notification/list', views.notification_list_view, name='notification_list'),
    path('notification/count', views.notification_count_view, name='notification_count'),

    path('get_vehicle_details/<str:id>', views.get_vehicle_details_view, name='get_vehicle_details'),
    path('get_buy_order_details/<uuid:id_buy_order>', views.get_buy_order_details_view, name='get_buy_order_details'),
    path('get_buy_order_uuid/<str:order_identifier>/', views.get_buy_order_uuid_view, name='get_buy_order_uuid'),
    path('get_fuel_orders/<uuid:id_buy_order>', views.get_fuel_orders_view, name='get_fuel_orders'),
    path('get_driver_details/<uuid:id>', views.get_driver_details_view, name='get_driver_details'),

    
]

sicomec/urls.py
from django.contrib import admin
from django.urls import path, include
from sicoapp.views import error_403

urlpatterns = [
    path('sicomec/admin/', admin.site.urls),
    path('sicomec/', include('sicoapp.urls')),
]

handler404 = 'sicoapp.views.error_404'
handler403 = error_403

sicoapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from .models import Driver, Vehicle, FuelTap, Ballot, Notification, BuyOrder, FuelOrder
from .forms import DriverForm, VehicleForm, FuelTapForm, BallotForm, BuyOrderForm, FuelOrderForm
from django.contrib import messages
from django.db.models import Q, Sum
from django.utils import timezone
from datetime import datetime
import pytz
from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
from babel.dates import format_datetime
from django.http import JsonResponse
from django.http import Http404
import re
from django.db import IntegrityError
from django.templatetags.static import static

# ************************************ GENERAL VIEWS ************************************

# HOME ---------------------------------------------------------------->
def home_view(request):
    return render(request, 'index.html')

# LOGIN --------------------------------------------------------------->
def login_view(request):
    if request.user.is_authenticated:
        return redirect('sicomec:home')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('sicomec:home')
            else:
                form.add_error(None, 'Usuario o contraseña incorrecto')
    else:
        form = AuthenticationForm(
            initial={'username': request.POST.get('username', '')})

    return render(request, 'login.html', {'form': form})

# LOGOUT --------------------------------------------------------------->
@login_required
def logout_view(request):
    logout(request)
    return redirect('sicomec:home')



# ************************************ DRIVER VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_driver', raise_exception=True)
def driver_create_view(request):
    if request.method == 'POST':
        form = DriverForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '¡Registro exitoso!')
            return redirect('sicomec:driver_list')  
    else:
        form = DriverForm()
    
    return render(request, 'drivers/driver_create.html', {'form': form})

# UPDATE ----------------------------------------------------------------->
@login_required
@permission_required('sicoapp.change_driver', raise_exception=True)
def driver_update_view(request, id):
    driver = get_object_or_404(Driver, pk=id)

    if request.method == 'POST':
        form = DriverForm(request.POST, instance=driver)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Actualización exitosa!')
            return redirect('sicomec:driver_list')
    else:
        formatted_expiration = driver.expiration.strftime('%Y-%m-%d')
        form = DriverForm(instance=driver, initial={'expiration': formatted_expiration})

    return render(request, 'drivers/driver_update.html', {'form': form, })

# LIST ------------------------------------------------------------------->
@login_required
@permission_required('sicoapp.view_driver', raise_exception=True)
def driver_list_view(request):
    results = Driver.objects.all()

    return render(request, 'drivers/driver_list.html', 
                {
                    'drivers': results,
                })

# DELETE ------------------------------------------------------------------>
@login_required
@permission_required('sicoapp.delete_driver', raise_exception=True)
def driver_delete_view(request, id):
    driver = get_object_or_404(Driver, pk=id)

    if Ballot.objects.filter(driver=driver.pk).exists():
        messages.warning(request, 'Conductor tiene papeleta asociada')
        return redirect('sicomec:driver_list')  

    if FuelOrder.objects.filter(driver=driver.pk).exists():
        messages.warning(request, 'Conductor tiene orden de compra asociada')
        return redirect('sicomec:driver_list')  
    
    driver.delete()
    messages.success(request, '¡Registro eliminado!')

    return redirect('sicomec:driver_list')  



# ************************************ VEHICLE VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_vehicle', raise_exception=True)
def vehicle_create_view(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '¡Registro exitoso!')
            return redirect('sicomec:vehicle_list')  
    else:
        form = VehicleForm()
    
    return render(request, 'vehicles/vehicle_create.html', {'form': form})

# UPDATE ----------------------------------------------------------------->
@login_required
@permission_required('sicoapp.change_vehicle', raise_exception=True)
def vehicle_update_view(request, id):
    vehicle = get_object_or_404(Vehicle, pk=id)

    if request.method == 'POST':
        form = VehicleForm(request.POST, instance=vehicle)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Actualización exitosa!')
            return redirect('sicomec:vehicle_list')
    else:
        form = VehicleForm(instance=vehicle, initial={
                            'soat': vehicle.soat.strftime('%Y-%m-%d') if vehicle.soat else '',
                            'citv': vehicle.citv.strftime('%Y-%m-%d') if vehicle.citv else '',
                            })

    return render(request, 'vehicles/vehicle_update.html', {'form': form,})

# LIST ------------------------------------------------------------------->
@login_required
@permission_required('sicoapp.view_vehicle', raise_exception=True)
def vehicle_list_view(request):
    results = Vehicle.objects.all()

    return render(request, 'vehicles/vehicle_list.html', {'vehicles': results,})

# DELETE ------------------------------------------------------------------>
@login_required
@permission_required('sicoapp.delete_vehicle', raise_exception=True)
def vehicle_delete_view(request, id):
    vehicle = get_object_or_404(Vehicle, pk=id)

    if Ballot.objects.filter(plate=vehicle.id).exists():
        messages.warning(request, 'Vehículo tiene papeleta asociada')
        return redirect('sicomec:vehicle_list')  

    if FuelOrder.objects.filter(plate=vehicle.id).exists():
        messages.warning(request, 'Vehículo tiene órden de compra asociada')
        return redirect('sicomec:vehicle_list')  
    
    vehicle.delete()
    messages.success(request, '¡Registro eliminado!')

    return redirect('sicomec:vehicle_list')  



# ************************************ FUELTAP VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_fueltap', raise_exception=True)
def fueltap_create_view(request):
    if request.method == 'POST':
        form = FuelTapForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '¡Registro exitoso!')
            return redirect('sicomec:fueltap_list')  
    else:
        form = FuelTapForm()
    
    return render(request, 'fueltaps/fueltap_create.html', {'form': form})

# UPDATE ----------------------------------------------------------------->
@login_required
@permission_required('sicoapp.change_fueltap', raise_exception=True)
def fueltap_update_view(request, id):
    fueltap = get_object_or_404(FuelTap, pk=id)

    if request.method == 'POST':
        form = FuelTapForm(request.POST, instance=fueltap)
        if form.is_valid():
            form.save()
            messages.success(request, '¡Actualización exitosa!')
            return redirect('sicomec:fueltap_list')
    else:
        form = FuelTapForm(instance=fueltap)

    return render(request, 'fueltaps/fueltap_update.html', {'form': form, })

# LIST ------------------------------------------------------------------->
@login_required
@permission_required('sicoapp.view_fueltap', raise_exception=True)
def fueltap_list_view(request):
    results = FuelTap.objects.all()

    return render(request, 'fueltaps/fueltap_list.html', {'fueltaps': results, })

# DELETE ------------------------------------------------------------------>
@login_required
@permission_required('sicoapp.delete_fueltap', raise_exception=True)
def fueltap_delete_view(request, id):
    fueltap = get_object_or_404(FuelTap, pk=id)

    if BuyOrder.objects.filter(fueltap=fueltap.pk).exists():
        messages.warning(request, 'Proveedor tiene orden de compra asociada')
    
    else:
        fueltap.delete()
        messages.success(request, '¡Registro eliminado!')

    return redirect('sicomec:fueltap_list')  



# ************************************ BUY ORDER VIEWS ************************************

# CREATE --------------------------------------------------------------->
@login_required
@permission_required('sicoapp.add_buyorder', raise_exception=True)
def buy_order_create_view(request):
    if request.method == 'POST':
        form = BuyOrderForm(request.POST)
        if form.is_valid():

            stock_value = form.cleaned_data['stock']
            buy_order_instance = form.save(commit=False)

sicoapp/templates/buy_orders/buy_order_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Registrar Orden de Compra | SICOMEC{% endblock %}

{% block content %}
    <div class="row">
        <section class="col-md-8 offset-md-2 my-5">
            <h3 class="text-center mb-3">Registrar Orden de Compra</h3>
            <form method="POST" enctype="multipart/form-data" class="card card-body mb-5">
                {% csrf_token %}
                <input type="hidden" id="form-instance-id" data-instance-id="{{ form.instance.user_area }}">
                {% crispy form %}
            </form>
        </section>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/buy_order_form.js' %}"></script>
{% endblock %}

sicoapp/templates/buy_orders/buy_order_list.html
{% extends 'base.html' %}
{% load static %}
{% load format_filters %}

{% block title %}Buscar Orden de Compra | SICOMEC{% endblock %}

{% block content %}
<div class="row">
    <section class="col-md-6 offset-md-3 mt-5">
        <h3 class="text-center mb-3" >Buscar Orden de Compra</h3>
    </section> 

    <section class="col-md-12" style="margin-bottom: 80px;">
            <div class="card card-body table-responsive">
                <table class="datatable display">
                    <thead>
                        <tr>
                            {% if is_super_admin or is_cadmin %}
                                <th>Acciones</th>
                            {% endif %}
                            <th>N° O/C</th>
                            <th>Área Usuaria</th>
                            <th>Proveedor</th>
                            <th>Combustible</th>
                            {% if not is_uquery %}
                                <th>Entrada</th>
                                <th>Saldo</th>
                            {% endif %}
                            <th>Fecha</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for buy_order in buy_orders %}
                            <tr>
                                {% if is_super_admin or is_cadmin %}
                                <td class="align-middle">
                                    <div class="btn-group">
                                        <a class="btn btn-sm btn-outline-primary " href="{% url 'sicomec:buy_order_update' buy_order.id %}">
                                            <i class="bi bi-pencil-fill" title="Editar"></i>
                                        </a>
                                        
                                        <a class="btn btn-sm btn-outline-danger" href="#" onclick="deleteRecord('/sicomec/buy_order/delete', '{{ buy_order.id }}', '', 'delete')" title="Eliminar">
                                            <i class="bi bi-trash-fill"></i>
                                        </a>
                                    
                                    </div>
                                </td>
                                {% endif %}

                                <td class="align-middle">{{ buy_order.order }}</td>
                                <td class="align-middle">
                                    <span class="d-inline-block text-truncate align-middle" style="max-width: 250px;">
                                        {{ buy_order.user_area }}
                                    </span>
                                </td>
                                <td class="align-middle">{{ buy_order.fueltap }}</td>
                                <td class="align-middle">{{ buy_order.fuel }}</td>
                                {% if not is_uquery %}
                                    <td class="align-middle number">{{ buy_order.stock|format_number }}</td>
                                    <td class="align-middle number">{{ buy_order.residue|format_number }}</td>
                                {% endif %}
                                <td class="align-middle">{{ buy_order.date|date:"d/m/Y" }}</td>
                            </tr>   
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    </section>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/datatables.js' %}"></script>
{% endblock %}

sicoapp/templates/buy_orders/buy_order_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Actualizar Orden de Compra | SICOMEC{% endblock %}

{% block content %}
    <div class="row">
        <section class="col-md-8 offset-md-2 my-5">
            <h3 class="text-center mb-3">
                <a class="btn btn-sm" href="{% url 'sicomec:buy_order_list' %}" title="Regresar" style="background-color: #072e5e;">
                    <i class="bi bi-arrow-left mx-1" style="font-size: 1rem; color: #fff;"></i>
                </a>
                Actualizar Orden de Compra
            </h3>
            <form method="POST" enctype="multipart/form-data" class="card card-body mb-5">
                {% csrf_token %}
                <input type="hidden" id="form-instance-id" data-instance-id="{{ form.instance.user_area }}">
                {% crispy form %}
            </form>
        </section>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/buy_order_form.js' %}"></script>
{% endblock %}